CREATE TABLE bots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bot_key VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  kind VARCHAR(50) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_bots_bot_key (bot_key)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE bot_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  bot_id BIGINT UNSIGNED NOT NULL,
  version_key VARCHAR(255) NOT NULL,
  version_label VARCHAR(100) NOT NULL,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_bot_versions_bot_version (bot_id, version_key),
  KEY ix_bot_versions_bot_created (bot_id, created_at),
  CONSTRAINT fk_bot_versions_bot FOREIGN KEY (bot_id) REFERENCES bots (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE match_series (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  mode VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  bot_one_version_id BIGINT UNSIGNED NOT NULL,
  bot_two_version_id BIGINT UNSIGNED NOT NULL,
  first_seat TINYINT UNSIGNED NOT NULL DEFAULT 0,
  repeat_count INT UNSIGNED NOT NULL,
  completed_match_count INT UNSIGNED NOT NULL DEFAULT 0,
  bot_one_wins INT UNSIGNED NOT NULL DEFAULT 0,
  bot_two_wins INT UNSIGNED NOT NULL DEFAULT 0,
  draw_count INT UNSIGNED NOT NULL DEFAULT 0,
  settings_json JSON NOT NULL,
  started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at TIMESTAMP(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_match_series_public_id (public_id),
  KEY ix_match_series_status_started (status, started_at),
  KEY ix_match_series_bot_one_started (bot_one_version_id, started_at),
  KEY ix_match_series_bot_two_started (bot_two_version_id, started_at),
  CONSTRAINT ck_match_series_first_seat CHECK (first_seat IN (0, 1)),
  CONSTRAINT ck_match_series_repeat_count CHECK (repeat_count BETWEEN 1 AND 500),
  CONSTRAINT fk_match_series_bot_one FOREIGN KEY (bot_one_version_id) REFERENCES bot_versions (id),
  CONSTRAINT fk_match_series_bot_two FOREIGN KEY (bot_two_version_id) REFERENCES bot_versions (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE matches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  series_id BIGINT UNSIGNED NULL,
  game_index INT UNSIGNED NULL,
  ruleset_version VARCHAR(100) NOT NULL,
  mode VARCHAR(50) NOT NULL,
  status VARCHAR(30) NOT NULL,
  outcome VARCHAR(50) NULL,
  termination_reason VARCHAR(100) NULL,
  bot_one_version_id BIGINT UNSIGNED NOT NULL,
  bot_two_version_id BIGINT UNSIGNED NOT NULL,
  first_seat TINYINT UNSIGNED NOT NULL DEFAULT 0,
  bot_one_reward DECIMAL(8, 4) NULL,
  bot_two_reward DECIMAL(8, 4) NULL,
  move_count INT UNSIGNED NOT NULL DEFAULT 0,
  duration_ms BIGINT UNSIGNED NULL,
  last_state_json JSON NULL,
  settings_json JSON NOT NULL,
  metadata_json JSON NOT NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at TIMESTAMP(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_matches_public_id (public_id),
  UNIQUE KEY uq_matches_series_game (series_id, game_index),
  KEY ix_matches_status_started (status, started_at),
  KEY ix_matches_outcome_started (outcome, started_at),
  KEY ix_matches_bot_one_started (bot_one_version_id, started_at),
  KEY ix_matches_bot_two_started (bot_two_version_id, started_at),
  CONSTRAINT ck_matches_first_seat CHECK (first_seat IN (0, 1)),
  CONSTRAINT fk_matches_series FOREIGN KEY (series_id) REFERENCES match_series (id),
  CONSTRAINT fk_matches_bot_one FOREIGN KEY (bot_one_version_id) REFERENCES bot_versions (id),
  CONSTRAINT fk_matches_bot_two FOREIGN KEY (bot_two_version_id) REFERENCES bot_versions (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE match_moves (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  match_id BIGINT UNSIGNED NOT NULL,
  ply INT UNSIGNED NOT NULL,
  seat TINYINT UNSIGNED NOT NULL,
  bot_version_id BIGINT UNSIGNED NOT NULL,
  source_square SMALLINT UNSIGNED NOT NULL,
  destination_square SMALLINT UNSIGNED NOT NULL,
  protocol_action SMALLINT UNSIGNED NOT NULL,
  think_time_ms INT UNSIGNED NULL,
  observation_json JSON NOT NULL,
  action_mask_json JSON NOT NULL,
  state_after_json JSON NOT NULL,
  reward_after DECIMAL(8, 4) NULL,
  is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_match_moves_match_ply (match_id, ply),
  KEY ix_match_moves_bot_action (bot_version_id, protocol_action),
  KEY ix_match_moves_match_seat (match_id, seat),
  CONSTRAINT ck_match_moves_seat CHECK (seat IN (0, 1)),
  CONSTRAINT ck_match_moves_protocol_action CHECK (protocol_action < 240),
  CONSTRAINT fk_match_moves_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
  CONSTRAINT fk_match_moves_bot_version FOREIGN KEY (bot_version_id) REFERENCES bot_versions (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
